dist: trusty
sudo: required
language: node_js
node_js:
- '11.10'
before_cache:
- nix-collect-garbage -d
- rm -rf node_modules/secp256k1/build
cache:
  npm: true
  directories:
  - nix
  timeout: 9000
before_install:
- . scripts/install-dapptools.sh
- npm i -g npm@latest yarn
install:
- yarn
before_script:
- npm install -g codecov
script:
- yarn build:backend
- yarn build:frontend
- yarn coverage
- yarn test:build
- codecov
after_install:
- cat /home/travis/.npm/_logs/2018-02-*.log
