dist: trusty
sudo: required
language: node_js
node_js:
- '10'
before_cache:
- nix-collect-garbage -d
cache:
  directories:
  - node_modules
  - nix
  timeout: 9000
before_install:
- . scripts/install-dapptools.sh
- npm i -g npm@latest
install:
- npm install
- npm run build:backend
- npm run build:frontend
before_script:
- npm install -g codecov
script:
- npm run coverage
- codecov
after_install:
- cat /home/travis/.npm/_logs/2018-02-*.log
